### ISSUE TITLE
Implementation using Vulkan-Hpp

### ISSUE THREAD

**Issue by Pacheco95** [KhronosGroup/Vulkan-Tutorial#37]
Hey guys! First of all, thanks for creting this tutorial. It helps a lot.
I have created an implementation for the tutorial using the Vulkan-Hpp binding, and I'll share it here.
If you think it is worth mentioning in the tutorial, feel free to add a link to it.

I tried to make it very flexible and all dependencies are managed by CMake.

https://github.com/Pacheco95/khronos-vulkan-tutorial-cpp

**Comment by SaschaWillems** [comment]
Just a quick note: I'm not a lawyer, but I don't think that it's okay to change the license to MIT. The original tutorial is licensed under [CC-BY-SA](https://creativecommons.org/licenses/by-sa/4.0/) which requires derived works to use the same license and give proper attribution, see https://github.com/KhronosGroup/Vulkan-Tutorial#attribution. That's why our version of the tutorial uses that same license.

**Comment by Pacheco95** [comment]
Updated the license

**Comment by SaschaWillems** [comment]
There are still MIT license files in the different chapter branches btw.

**Comment by SaschaWillems** [comment]
Btw. we don't actually link to other versions of the tutorial right now.
